apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: 
    app: user
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: 
      app: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels: 
        app: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: "daliparthy/user:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: user