- name: Play to configure catalogue component
  become: true
  hosts: catalogue
  tasks:
  - name: "Disable default nodejs module"
    ansible.builtin.command: dnf module disable nodejs -y

  - name: "Enable nodejs:18 version module"
    ansible.builtin.command: dnf module enable nodejs:18 -y

  - name: "Install nodejs"
    ansible.builtin.dnf:
      name: "nodejs"
      state: present

  - name: "Create roboshop user"
    ansible.builtin.user:
      name: roboshop

  - name: "Recursively remove app directory"
    ansible.builtin.file:
      path: /app
      state: absent

  - name: "Create application directory"
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Download application code"
    ansible.builtin.get_url:
      url: https://robotshop-builds.s3.us-east-1.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: "Install unzip if not present"
    ansible.builtin.yum:
      name: unzip
      state: present

  - name: "Extract the catalogue application code"
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: "Install application dependencies"
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: "Configure systemd service for catalogue"
    ansible.builtin.copy:
      src: "catalogue.service"
      dest: "/etc/systemd/system/catalogue.service"

  - name: "Daemon reload and start"
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: "Configure mongodb repository"
    ansible.builtin.copy:
      src: "mongodb.repo"
      dest: "/etc/yum.repos.d/mongodb.repo"

  - name: "Install mongodb client"
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: "Get the categories count"
    ansible.builtin.command:  mongo --host mongodb.myroboshop.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: "Load catalogue data"
    ansible.builtin.command: mongo --host mongodb.myroboshop.online < /app/schema/catalogue.js
    when: product_count.stdout == "0"

  - name: "Start and enable catalogue service"
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes  
