- name: Play to configure mongodb component
  become: true
  hosts: mongodb
  tasks:
  - name: "Configure YUM" 
    ansible.builtin.copy:
      src: "mongodb.repo"
      dest: "/etc/yum.repos.d/mongodb.repo"
      
  - name: "Install mongodb client" 
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: "Start and enable mongod service"
    ansible.builtin.service:
      service: mongod
      state: started
      enabled: yes

  - name: "Allow remote conncections"
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      
  - name: Restart mongod service
    ansible.builtin.service:
      service: mongod
      state: restarted