- name: Play to configure payment component
  become: true
  hosts: payment 
  tasks:
  - name: "Install python packages"
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present 
    loop:
      - python36
      - gcc
      - python3-devel

  - name: "Create roboshop user"
    ansible.builtin.user:
      name: roboshop

  - name: "Recursively remove app directory"
    ansible.builtin.file:
      path: /app
      state: absent

  - name: "Create application directory"
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Download application code"
    ansible.builtin.get_url:
      url: https://robotshop-builds.s3.us-east-1.amazonaws.com/payment.zip
      dest: /tmp

  - name: "Install unzip if not present"
    ansible.builtin.yum:
      name: unzip
      state: present

  - name: "Extract the payment application code"
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: "Install application dependencies"
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app

  - name: "Configure systemd service for payment"
    ansible.builtin.copy:
      src: "cart.service"
      dest: "/etc/systemd/system/payment.service"

  - name: "Daemon reload and start"
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: "Start and enable cart service"
    ansible.builtin.service:
      name: payment 
      state: restarted
      enabled: yes  
