- name: Play to configure user component
  become: true
  hosts: user
  tasks:
  - name: "Disable default nodejs module"
    ansible.builtin.command: dnf module disable nodejs -y

  - name: "Enable nodejs:18 version module"
    ansible.builtin.command: dnf module enable nodejs:18 -y

  - name: "Install nodejs"
    ansible.builtin.dnf:
      name: "nodejs"
      state: present

  - name: "Create roboshop user"
    ansible.builtin.user:
      name: roboshop

  - name: "Recursively remove app directory"
    ansible.builtin.file:
      path: /app
      state: absent

  - name: "Create application directory"
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Download application code"
    ansible.builtin.get_url:
      url: https://robotshop-builds.s3.us-east-1.amazonaws.com/user.zip
      dest: /tmp

  - name: "Install unzip if not present"
    ansible.builtin.yum:
      name: unzip
      state: present

  - name: "Extract the user application code"
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: "Install application dependencies"
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: "Configure systemd service for user"
    ansible.builtin.copy:
      src: "user.service"
      dest: "/etc/systemd/system/user.service"

  - name: "Daemon reload and start"
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: "Copy mongodb repo"
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: "Install mongodb client"
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: "Get the users count"
    ansible.builtin.command:  mongo --host mongodb.myroboshop.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: "load user data"
    ansible.builtin.command: mongo --host mongodb.myroboshop.online < /app/schema/user.js
    when: user_count.stdout == "0"

  - name: "Start and enable user service"
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes  
